pipelines:
  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline
    success-message: Build succeeded (gate pipeline).
    failure-message: Build failed (gate pipeline).
    source: gerrit
    manager: DependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - code-review: 2
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
#        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2

  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    success-message: Build succeeded (check pipeline).
    failure-message: Build failed (check pipeline).
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: post-merge
    description: This pipeline runs jobs that operate after changes are merged.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: change-merged

projects:
  - name: final-test
    gate:
      - dev-unit-tests-before-merge-prod
    check:
      - dev-unit-test-patchset
    post-merge:
      - copy-dev-merge-to-prod
